USE [master]
GO

/****** Object:  Database [UsersDb]    Script Date: 6/21/2021 4:40:08 PM ******/
CREATE DATABASE [UsersDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UsersDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\UsersDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UsersDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\UsersDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UsersDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UsersDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UsersDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UsersDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UsersDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UsersDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [UsersDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UsersDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UsersDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UsersDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UsersDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UsersDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UsersDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UsersDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UsersDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UsersDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UsersDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UsersDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UsersDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UsersDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UsersDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UsersDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UsersDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UsersDb] SET RECOVERY FULL 
GO

ALTER DATABASE [UsersDb] SET  MULTI_USER 
GO

ALTER DATABASE [UsersDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UsersDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UsersDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UsersDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UsersDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UsersDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [UsersDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [UsersDb] SET  READ_WRITE 
GO

